package tr.com.idefix.domain.constants;

/**
 * Created by utkan on 02/09/15.
 */
public interface Keys {
  String LOGGEDIN_USER_CACHE_KEY = "LOGGEDIN_USER_CACHE_KEY";
  String LOGGEDIN_USER_INFO_CACHE_KEY = "LOGGEDIN_USER_INFO_CACHE_KEY";
  String COUNTRIES_CACHE_KEY = "COUNTRIES_CACHE_KEY";
  //    String MAIN_CATEGORIES_CACHE_KEY = "MAIN_CATEGORIES_CACHE_KEY";
  //    String BANNERS_CACHE_KEY = "BANNERS_CACHE_KEY";
  String STORES_CACHE_KEY = "STORES_CACHE_KEY";
  String CATEGORY_TREE_CACHE_KEY = "CATEGORY_TREE_CACHE_KEY";
  String PERMISSION_ASKED = "PERMISSION_ASKED";
  String IS_BARCODE_INFO_SHOWN = "IS_BARCODE_INFO_SHOWN";
  //    String WISHES_CACHE_KEY = "WISHES_CACHE_KEY";
}
